/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TranslateDialog: typeof import('./src/components/TranslateDialog.vue')['default']
    TranslateEffect: typeof import('./src/components/TranslateEffect.vue')['default']
    TranslatePage: typeof import('./src/components/TranslatePage.vue')['default']
    TranslateUpload: typeof import('./src/components/TranslateUpload.vue')['default']
  }
}
